export const PLAN_OPTIONS = [
  {
    key: "free",
    maxCustomers: 10,
    maxCharges: 20,
    title: "Grátis",
    monthlyPrice: "0",
    annualPrice: "0",
    desc: "Para começar a organizar suas cobranças sem pagar nada.",
    items: [
      "Até 10 clientes",
      "Até 20 cobranças por mês",
      "Dashboard financeiro",
      "WhatsApp via link",
      "Controle de recebimentos",
    ],
    monthlyCheckout: null,
    annualCheckout: null,
    free: true,
  },
  {
    key: "essencial",
    maxCustomers: 50,
    maxCharges: 150,
    title: "Essencial",
    monthlyPrice: "49,90",
    annualPrice: "478,80",
    desc: "Para pequenos negócios que querem mais controle e organização.",
    items: [
      "Até 50 clientes",
      "Até 150 cobranças por mês",
      "Dashboard financeiro completo",
      "WhatsApp via link",
      "Relatórios financeiros",
      "Controle de recebimentos",
    ],
    monthlyCheckout: "https://go.perfectpay.com.br/PPU38CQGH3N",
    annualCheckout: "https://go.perfectpay.com.br/PPU38CQGH44",
  },
  {
    key: "profissional",
    maxCustomers: 200,
    maxCharges: 500,
    title: "Profissional",
    monthlyPrice: "99,90",
    annualPrice: "958,80",
    desc: "Para empresas que precisam de mais automação e controle no dia a dia.",
    items: [
      "Até 200 clientes",
      "Até 500 cobranças por mês",
      "Tudo do Essencial",
      "Assistente IA",
      "Relatórios avançados",
      "Suporte prioritário",
    ],
    monthlyCheckout: "https://go.perfectpay.com.br/PPU38CQGH3Q",
    annualCheckout: "https://go.perfectpay.com.br/PPU38CQGH48",
  },
  {
    key: "business",
    maxCustomers: null,
    maxCharges: null,
    title: "Business",
    monthlyPrice: "199,90",
    annualPrice: "1.918,80",
    desc: "Para operações maiores e equipes que precisam de mais capacidade.",
    items: [
      "Clientes ilimitados",
      "Cobranças ilimitadas",
      "Tudo do Profissional",
      "Mais usuários",
      "Maior capacidade de uso",
      "Atendimento prioritário",
    ],
    monthlyCheckout: "https://go.perfectpay.com.br/PPU38CQGH3R",
    annualCheckout: "https://go.perfectpay.com.br/PPU38CQGH4A",
  },
];
