export const PLAN_OPTIONS = [
  {
    key: "free",
    title: "Grátis",
    monthlyPrice: "0",
    annualPrice: "0",
    desc: "Para começar a organizar suas cobranças sem pagar nada.",
    items: [
      "Até 10 clientes",
      "Até 20 cobranças por mês",
      "Dashboard financeiro",
      "WhatsApp via link",
      "Controle de recebimentos",
    ],
    monthlyCheckout: null,
    annualCheckout: null,
    free: true,
  },
  {
    key: "essencial",
    title: "Essencial",
    monthlyPrice: "49,90",
    annualPrice: "478,80",
    desc: "Para pequenos negócios que querem mais controle e organização.",
    items: [
      "Clientes e cobranças ilimitados",
      "Dashboard financeiro completo",
      "WhatsApp via link",
      "Relatórios financeiros",
      "Controle de recebimentos",
      "Histórico de cobranças",
    ],
    monthlyCheckout: "https://go.perfectpay.com.br/PPU38CQGH3N",
    annualCheckout: "https://go.perfectpay.com.br/PPU38CQGH44",
  },
  {
    key: "profissional",
    title: "Profissional",
    monthlyPrice: "99,90",
    annualPrice: "958,80",
    desc: "Para empresas que precisam automatizar mais tarefas no dia a dia.",
    items: [
      "Tudo do Essencial",
      "Assistente IA",
      "Relatórios avançados",
      "Mais recursos de gestão",
      "Suporte prioritário",
      "Mais limites de uso",
    ],
    monthlyCheckout: "https://go.perfectpay.com.br/PPU38CQGH3Q",
    annualCheckout: "https://go.perfectpay.com.br/PPU38CQGH48",
  },
  {
    key: "business",
    title: "Business",
    monthlyPrice: "199,90",
    annualPrice: "1.918,80",
    desc: "Para operações maiores e equipes que precisam de mais capacidade.",
    items: [
      "Tudo do Profissional",
      "Recursos avançados",
      "Mais usuários",
      "Maior capacidade de uso",
      "Atendimento prioritário",
      "Recursos para equipes",
    ],
    monthlyCheckout: "https://go.perfectpay.com.br/PPU38CQGH3R",
    annualCheckout: "https://go.perfectpay.com.br/PPU38CQGH4A",
  },
];
